# Optimized Gradle Daemon memory settings to prevent disk paging / thrashing
org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Gradle build accelerations
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.daemon=true

# Android & Kotlin flags
android.useAndroidX=true
# Fix Windows cross-drive (C: pub cache vs E: project) Kotlin incremental cache bug
kotlin.incremental=false
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false


