# Optimized Gradle Daemon memory settings to prevent disk paging / thrashing
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:ReservedCodeCacheSize=512m -XX:+UseParallelGC -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED

# Gradle build accelerations
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.daemon=true

# Android & Kotlin flags
android.useAndroidX=true
kotlin.incremental=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false




# Speed
kotlin.daemon.jvmargs=-Xmx2g
android.nonTransitiveRClass=true
